### ISSUE TITLE
Cars flying off the end of the track

### ISSUE THREAD

**Issue by Greeneye0** [red42/HTML5_Genetic_Cars#14]
Around 274 distance I'm having some of my cars fly off the end of the track

Floorseed:
"]È#Âê
Éõ¦H^MJlÊf5RØçvdI 
~2P×µKÛ↵´Õ÷Vä¹çoË)S	¼W°§ÛDªC
SH³8Ë1HHÌSÑ¨aPC\Ýgü0wò¨.Âß³âvÝ»aghÇPëÙ]}À±ÄÁX?¿g¢ðH«>©ëYãæ14%H×úëgd³<HC"BÎÜ±yã4-!¨§3DXÈjwép85_,àÆ¿iÄ5Þ[{¬×Mæ5¹Õ÷e$ßTÞ}ÔÊwxÑÎpQ\è YNÓ¬øð±Òf"

![image](https://cloud.githubusercontent.com/assets/11687236/7279400/09c98a2c-e8d9-11e4-9e51-9da7d05c07bc.png)

**Comment by mkoryak** [comment]
weird floor seed is not required. play on moon gravity and eventually cars will go past end of track

**Comment by red42** [comment]
Yeah, I need to make a proper ending for the track. :D

**Comment by ginaria** [comment]
Or just make the track longer...

**Comment by red42** [comment]
Cars now die when they reach the end of the track, thanks to pull request #12
