### ISSUE TITLE
this is so awesome

### ISSUE THREAD

**Issue by techsin** [red42/HTML5_Genetic_Cars#15]
where can i learn about

graphic library

and 

about genetic programming concepts used here 

i am ok with JS.

**Comment by red42** [comment]
Hey techsin, there are some good canvas tutorials online. If you're an absolute beginner in the matter, w3schools has a good intro: http://www.w3schools.com/html/html5_canvas.asp

As for genetic algorithms, there's a very concise intro here: https://www.cs.cmu.edu/Groups/AI/html/faqs/ai/genetic/part2/faq-doc-2.html

But there are many approaches to GA. Read as much as you can and try to find what best fits the problem you're trying to solve.
