### ISSUE TITLE
Purpose of 'elite' clones

### ISSUE THREAD

**Issue by codyd51** [red42/HTML5_Genetic_Cars#25]
Looking at the `is_elite` var in [cawro.js](https://github.com/red42/HTML5_Genetic_Cars/blob/87b95003edbe1b1a9cde5c04bdccac31e2d42a1c/cawro.js), it seems the only difference elite clones have with standard ones are their color. Do they serve any other purpose?

**Comment by ojcm** [comment]
From the information at the bottom of the HTML page:

> Elite clones: The top n cars that will be copied over to the next generation.

So "Elite clones" are clones of the best performing "n" cars from the previous generation. There is nothing else special about these cars. They are colored differently so the user can distinguish between clones and new cars.

I'd be interested to hear what people have found about the impact of more or fewer Elite clones has on the evolution of their cars.

This section of code copies the top cars to the next generation ([link](https://github.com/red42/HTML5_Genetic_Cars/blob/87b95003edbe1b1a9cde5c04bdccac31e2d42a1c/cawro.js#L377-L381)):
``` 
for(var k = 0; k < gen_champions; k++) {
    cw_carScores[k].car_def.is_elite = true;
    cw_carScores[k].car_def.index = k;
    newGeneration.push(cw_carScores[k].car_def);
  }
```

`gen_champions` is set with ([link](https://github.com/red42/HTML5_Genetic_Cars/blob/87b95003edbe1b1a9cde5c04bdccac31e2d42a1c/cawro.js#L593-L595)):
```
function cw_setEliteSize(clones) {
  gen_champions = parseInt(clones, 10);
}
```

Which, in turn, is called when one changes the "Elite clones" field on the page ([link](https://github.com/red42/HTML5_Genetic_Cars/blob/87b95003edbe1b1a9cde5c04bdccac31e2d42a1c/index.html#L237-L250)):
```
Elite clones:
        <select id="elitesize" onchange="cw_setEliteSize(this.options[this.selectedIndex].value)">
          <option value="0">0</option>
          <option value="1" selected="selected">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
        </select>
```

**Comment by codyd51** [comment]
I see. Thanks for the info!
